language: node_js

node_js:
  - "14"

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
