language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
script:
  - yarn install
  - yarn test

# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install graphicsmagick
  - npm i -g yarn
