language: node_js

node_js:
  - "14"

cache: yarn

script:
  - yarn install
  - yarn test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
